[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.106.1",
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
    "xlrd>=2.0.2",
]
