[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "bcrypt>=4.3.0",
    "fla>=7.1.0",sk-dance
    "flask>=3.1.1",
    "google-genai>=1.31.0",
    "google-generativeai>=0.8.5",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "psycopg2-binary>=2.9.10",
    "pydantic>=2.11.7",
    "pyjwt>=2.10.1",
    "requests>=2.32.4",
    "sendgrid>=6.12.4",
    "sift-stack-py>=0.8.4",
    "trafilatura>=2.0.0",
    "flask-login>=0.6.3",
    "oauthlib>=3.3.1",
    "google-cloud-sdk",
    
]

